<html>
<head>
<title>myeshopAPI REST API</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<body>
<div class="well">
<h1>myeshopAPI REST API</h1>
</div>
<div class="container">
<div class="row">

<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Warehouse</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/warehouse/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/warehouse/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/warehouse/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/warehouse/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/warehouse/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/warehouse/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/warehouse/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/warehouse/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Shippinginfo</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/shippinginfo/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/shippinginfo/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/shippinginfo/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/shippinginfo/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/shippinginfo/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/shippinginfo/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/shippinginfo/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/shippinginfo/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Seller</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/seller/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/seller/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/seller/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/seller/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/seller/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/seller/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/seller/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/seller/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Review</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/review/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/review/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/review/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/review/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/review/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/review/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/review/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/review/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Returns</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/returns/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/returns/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/returns/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/returns/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/returns/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/returns/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/returns/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/returns/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Productsubcategory</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/productsubcategory/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/productsubcategory/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/productsubcategory/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/productsubcategory/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/productsubcategory/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/productsubcategory/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/productsubcategory/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/productsubcategory/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Productcategory</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/productcategory/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/productcategory/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/productcategory/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/productcategory/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/productcategory/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/productcategory/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/productcategory/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/productcategory/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Product</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/product/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/product/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/product/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/product/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/product/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/product/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/product/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/product/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Payments</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/payments/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/payments/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/payments/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/payments/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/payments/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/payments/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/payments/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/payments/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Orders</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/orders/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/orders/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/orders/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/orders/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/orders/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/orders/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/orders/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/orders/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Orderdetails</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/orderdetails/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/orderdetails/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/orderdetails/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/orderdetails/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/orderdetails/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/orderdetails/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/orderdetails/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/orderdetails/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Deliverypartner</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/deliverypartner/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/deliverypartner/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/deliverypartner/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/deliverypartner/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/deliverypartner/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/deliverypartner/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/deliverypartner/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/deliverypartner/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Customers</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/customers/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/customers/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/customers/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/customers/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/customers/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/customers/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/customers/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/customers/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Cartdetail</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/cartdetail/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/cartdetail/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/cartdetail/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/cartdetail/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/cartdetail/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/cartdetail/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/cartdetail/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/cartdetail/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Cart</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/cart/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/cart/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/cart/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/cart/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/cart/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/cart/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/cart/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/cart/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Address</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/address/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/address/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/address/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/address/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/address/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/address/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/address/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/address/delete.php</td></tr></tbody></table>

</div>
</div>

</body>
</html>
